# Generated by Django 4.0.4 on 2022-05-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
