# Generated by Django 4.0.4 on 2022-05-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_analysis_data_alter_analysis_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
