# Generated by Django 4.0.4 on 2022-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_analysis_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='stdout',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (0, 'Failed')], null=True),
        ),
    ]
